/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LeerTeclasUsandoCPP */

#ifndef _Included_LeerTeclasUsandoCPP
#define _Included_LeerTeclasUsandoCPP
#ifdef __cplusplus
extern "C" {
#endif
#undef LeerTeclasUsandoCPP_STOP
#define LeerTeclasUsandoCPP_STOP 0L
#undef LeerTeclasUsandoCPP_ARRIBA
#define LeerTeclasUsandoCPP_ARRIBA 119L
#undef LeerTeclasUsandoCPP_ABAJO
#define LeerTeclasUsandoCPP_ABAJO 115L
#undef LeerTeclasUsandoCPP_IZQUIERDA
#define LeerTeclasUsandoCPP_IZQUIERDA 97L
#undef LeerTeclasUsandoCPP_DERECHA
#define LeerTeclasUsandoCPP_DERECHA 100L
#undef LeerTeclasUsandoCPP_ESC
#define LeerTeclasUsandoCPP_ESC 27L
/*
 * Class:     LeerTeclasUsandoCPP
 * Method:    leerTecla
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LeerTeclasUsandoCPP_leerTecla
  (JNIEnv *, jobject);

/*
 * Class:     LeerTeclasUsandoCPP
 * Method:    hayTeclaPulsada
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LeerTeclasUsandoCPP_hayTeclaPulsada
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
